### ISSUE TITLE
Automatically bump version dependencies

### ISSUE THREAD

**Issue by erfanium** [denodrivers/mongo#422]
A suggestion from @williamhorning 
```yml
on:
  schedule:
   - cron: "0 23 * * *"

jobs:
  check_dependencies:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno outdated > /tmp/deno_log
      - run: deno outdated --update
      - uses: peter-evans/create-pull-request@v7
        with:
          branch: bump-version
          title: 'chore: bump version'
          body-path: /tmp/deno_log
```

**Comment by williamhorning** [comment]
i've created a github action [here](https://github.com/williamhorning/deno-outdated-action) which should accomplish what you want using the following workflow code, however, the action does require you to change the action settings to allow it to make pull requests. if you'd like, i can make a pr adding this. also, if possible, could you create a new release on JSR with the updated version of web_bson?

```yml
on:
  schedule:
   - cron: "0 23 * * *"

jobs:
  update:
    run-on: ubuntu-latest
    steps:
      - uses: williamhorning/deno-outdated-action@v1
        with:
          branch_name: "bump-version"
          commit_message: "chores: update Deno dependencies"
          deno_version: "2.x"
          pull_request_title: "chore: update Deno dependencies"
```

![workflow permissions page showing read + write permissions along with allowing it to make pull requests](https://github.com/user-attachments/assets/e10edf69-60e1-46a4-b1c2-79f5a6e3676a)
